version: '3'

services:
  database:
    image: postgres:17
    container_name: portfolio_db
    restart: always
    environment:
      POSTGRES_DB: portfolio_tut
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio_app
    depends_on:
      - database
    volumes:
      - ./upload-dir:/app/upload-dir
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8080:8080"
    networks:
      - backend

networks:
  backend:

volumes:
  db_data:
