version: '3'

services:
  database:
    image: postgres:17
    container_name: portfolio_db
    restart: always
    environment:
      POSTGRES_DB: portfolio_tut
      POSTGRES_USER: lord_tut
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - backend

  app:
    build:
      context: .
      dockerfile: Dockerfile    # This assumes your Dockerfile is in the current directory
    container_name: portfolio_app
    depends_on:
      - database
    volumes:
      - ./upload-dir:/app/upload-dir
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/portfolio_tut
      SPRING_DATASOURCE_USERNAME: lord_tut
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"
    networks:
      - backend

networks:
  backend:
