--
-- PostgreSQL database dump
--

-- Dumped from database version 17.4
-- Dumped by pg_dump version 17.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: achievement_types; Type: TABLE; Schema: public; Owner: lord_tut
--

CREATE TABLE public.achievement_types (
    id bigint NOT NULL,
    name character varying(255) NOT NULL
);


ALTER TABLE public.achievement_types OWNER TO lord_tut;

--
-- Name: achievement_types_seq; Type: SEQUENCE; Schema: public; Owner: lord_tut
--

CREATE SEQUENCE public.achievement_types_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.achievement_types_seq OWNER TO lord_tut;

--
-- Name: achievements; Type: TABLE; Schema: public; Owner: lord_tut
--

CREATE TABLE public.achievements (
    id bigint NOT NULL,
    description character varying(255) NOT NULL,
    git_hub_link character varying(255),
    name character varying(255) NOT NULL,
    type_id bigint NOT NULL
);


ALTER TABLE public.achievements OWNER TO lord_tut;

--
-- Name: achievements_seq; Type: SEQUENCE; Schema: public; Owner: lord_tut
--

CREATE SEQUENCE public.achievements_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.achievements_seq OWNER TO lord_tut;

--
-- Name: achievements_technologies; Type: TABLE; Schema: public; Owner: lord_tut
--

CREATE TABLE public.achievements_technologies (
    achie_id bigint NOT NULL,
    tech_id bigint NOT NULL
);


ALTER TABLE public.achievements_technologies OWNER TO lord_tut;

--
-- Name: admin; Type: TABLE; Schema: public; Owner: lord_tut
--

CREATE TABLE public.admin (
    id bigint NOT NULL,
    password character varying(255) NOT NULL,
    username character varying(255) NOT NULL
);


ALTER TABLE public.admin OWNER TO lord_tut;

--
-- Name: admin_id_seq; Type: SEQUENCE; Schema: public; Owner: lord_tut
--

ALTER TABLE public.admin ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.admin_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: persons; Type: TABLE; Schema: public; Owner: lord_tut
--

CREATE TABLE public.persons (
    id bigint NOT NULL,
    name character varying(255)
);


ALTER TABLE public.persons OWNER TO lord_tut;

--
-- Name: persons_seq; Type: SEQUENCE; Schema: public; Owner: lord_tut
--

CREATE SEQUENCE public.persons_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.persons_seq OWNER TO lord_tut;

--
-- Name: posts; Type: TABLE; Schema: public; Owner: lord_tut
--

CREATE TABLE public.posts (
    id bigint NOT NULL,
    descreption character varying(255),
    person_id bigint NOT NULL
);


ALTER TABLE public.posts OWNER TO lord_tut;

--
-- Name: posts_seq; Type: SEQUENCE; Schema: public; Owner: lord_tut
--

CREATE SEQUENCE public.posts_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.posts_seq OWNER TO lord_tut;

--
-- Name: technologies; Type: TABLE; Schema: public; Owner: lord_tut
--

CREATE TABLE public.technologies (
    id bigint NOT NULL,
    name character varying(255)
);


ALTER TABLE public.technologies OWNER TO lord_tut;

--
-- Name: technologies_seq; Type: SEQUENCE; Schema: public; Owner: lord_tut
--

CREATE SEQUENCE public.technologies_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.technologies_seq OWNER TO lord_tut;

--
-- Name: visuals; Type: TABLE; Schema: public; Owner: lord_tut
--

CREATE TABLE public.visuals (
    visual_link character varying(255) NOT NULL,
    description character varying(255),
    achievement_id bigint NOT NULL
);


ALTER TABLE public.visuals OWNER TO lord_tut;

--
-- Name: achievement_types achievement_types_pkey; Type: CONSTRAINT; Schema: public; Owner: lord_tut
--

ALTER TABLE ONLY public.achievement_types
    ADD CONSTRAINT achievement_types_pkey PRIMARY KEY (id);


--
-- Name: achievements achievements_pkey; Type: CONSTRAINT; Schema: public; Owner: lord_tut
--

ALTER TABLE ONLY public.achievements
    ADD CONSTRAINT achievements_pkey PRIMARY KEY (id);


--
-- Name: admin admin_pkey; Type: CONSTRAINT; Schema: public; Owner: lord_tut
--

ALTER TABLE ONLY public.admin
    ADD CONSTRAINT admin_pkey PRIMARY KEY (id);


--
-- Name: persons persons_pkey; Type: CONSTRAINT; Schema: public; Owner: lord_tut
--

ALTER TABLE ONLY public.persons
    ADD CONSTRAINT persons_pkey PRIMARY KEY (id);


--
-- Name: posts posts_pkey; Type: CONSTRAINT; Schema: public; Owner: lord_tut
--

ALTER TABLE ONLY public.posts
    ADD CONSTRAINT posts_pkey PRIMARY KEY (id);


--
-- Name: technologies technologies_pkey; Type: CONSTRAINT; Schema: public; Owner: lord_tut
--

ALTER TABLE ONLY public.technologies
    ADD CONSTRAINT technologies_pkey PRIMARY KEY (id);


--
-- Name: achievement_types uk6wmjni9fedpno3973bgdctifw; Type: CONSTRAINT; Schema: public; Owner: lord_tut
--

ALTER TABLE ONLY public.achievement_types
    ADD CONSTRAINT uk6wmjni9fedpno3973bgdctifw UNIQUE (name);


--
-- Name: admin ukgfn44sntic2k93auag97juyij; Type: CONSTRAINT; Schema: public; Owner: lord_tut
--

ALTER TABLE ONLY public.admin
    ADD CONSTRAINT ukgfn44sntic2k93auag97juyij UNIQUE (username);


--
-- Name: achievements ukktpif54u9a3ssn6rpxxqx6jvp; Type: CONSTRAINT; Schema: public; Owner: lord_tut
--

ALTER TABLE ONLY public.achievements
    ADD CONSTRAINT ukktpif54u9a3ssn6rpxxqx6jvp UNIQUE (name);


--
-- Name: visuals visuals_pkey; Type: CONSTRAINT; Schema: public; Owner: lord_tut
--

ALTER TABLE ONLY public.visuals
    ADD CONSTRAINT visuals_pkey PRIMARY KEY (achievement_id, visual_link);


--
-- Name: achievements_technologies fk3hrnglvwwana2bxlprow3c5hb; Type: FK CONSTRAINT; Schema: public; Owner: lord_tut
--

ALTER TABLE ONLY public.achievements_technologies
    ADD CONSTRAINT fk3hrnglvwwana2bxlprow3c5hb FOREIGN KEY (tech_id) REFERENCES public.technologies(id);


--
-- Name: achievements_technologies fkd5gbvd3k7e8ymnafabq6yheq7; Type: FK CONSTRAINT; Schema: public; Owner: lord_tut
--

ALTER TABLE ONLY public.achievements_technologies
    ADD CONSTRAINT fkd5gbvd3k7e8ymnafabq6yheq7 FOREIGN KEY (achie_id) REFERENCES public.achievements(id);


--
-- Name: visuals fkk3ngxl41h99f4mkwnq83vcujl; Type: FK CONSTRAINT; Schema: public; Owner: lord_tut
--

ALTER TABLE ONLY public.visuals
    ADD CONSTRAINT fkk3ngxl41h99f4mkwnq83vcujl FOREIGN KEY (achievement_id) REFERENCES public.achievements(id);


--
-- Name: achievements fkmo6m290wsq95a6y226ynky0a8; Type: FK CONSTRAINT; Schema: public; Owner: lord_tut
--

ALTER TABLE ONLY public.achievements
    ADD CONSTRAINT fkmo6m290wsq95a6y226ynky0a8 FOREIGN KEY (type_id) REFERENCES public.achievement_types(id);


--
-- Name: posts fkoehc0y5se21rdwbf0j2dhr2bq; Type: FK CONSTRAINT; Schema: public; Owner: lord_tut
--

ALTER TABLE ONLY public.posts
    ADD CONSTRAINT fkoehc0y5se21rdwbf0j2dhr2bq FOREIGN KEY (person_id) REFERENCES public.persons(id);


--
-- PostgreSQL database dump complete
--

